# Generated by Django 4.2.11 on 2024-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place_info', models.TextField()),
                ('best_time_to_visit', models.DateTimeField(verbose_name='best time to visit')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
